name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '14 1 * * *'

jobs:    
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        nixPath:
          - nixpkgs=channel:nixpkgs-unstable
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=channel:nixos-20.03
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v9
      with:
        skip_adding_nixpkgs_channel: true
    - name: Setup NIX_PATH
      run: echo "::set-env name=NIX_PATH::${{ matrix.nixPath }}"
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup cachix
      uses: cachix/cachix-action@v6
      with:
        name: nikolasm
        skipPush: true
    - name: Build and test all attributes
      run: nix-build ci.nix -A buildOutputs
    - name: Setup cachix push
      uses: cachix/cachix-action@v6
      with:
        name: nikolasm
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build, test and push cacheable attributes
      run: nix-build ci.nix -A cacheOutputs
    - name: Test lib
      run: nix eval -f default.nix 'lib'
    - name: Test modules
      run: nix eval -f default.nix 'modules'
    - name: Test overlays
      run: nix eval -f default.nix 'overlays'
    - name: Trigger NUR update
      run: curl -XPOST "https://nur-update.herokuapp.com/update?repo=n1kolasM"
